import json
import os

notebook_path = r"d:\Project Analysis Personal\Data Banking Portofolio\notebooks\macro_banking_equity_analysis.ipynb"
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 📊 Macroeconomic Impact on Indonesian Banking Sector & Equity Performance\n",
            "**Author:** Data Analyst Portfolio Project  \n",
            "**Focus Area:** Financial Economics, Banking Health (OJK), Monetary Policy (Bank Indonesia), & Equity Valuation (The Big 4 Banks: BBCA, BBRI, BMRI, BBNI)  \n",
            "# 🏛️ 3 Pilar Perbankan Indonesia: Analisis Ekuitas & Transmisi Makroekonomi\n",
            "**Analisis Komparatif:** Bank BUMN vs Bank Swasta (BUSN) vs Bank Syariah  \n",
            "**Fokus Studi:** Kebijakan Moneter (BI-Rate), Volatilitas Valas (USD/IDR), Fundamental Intermediasi (OJK SPI & SPS), dan Kinerja Saham Pasar Modal  \n",
            "\n",
            "---\n",
            "\n",
            "## 1. Executive Summary & Business Problem\n",
            "Sektor perbankan merupakan tulang punggung sistem keuangan dan kapitalisasi pasar modal Indonesia (IHSG). Bank-bank buku besar (*The Big 4*: BCA, BRI, Mandiri, BNI) sangat sensitif terhadap dua variabel makroekonomi utama:\n",
            "1. **Suku Bunga Acuan (BI-Rate)**: Mempengaruhi *Cost of Funds* (CoF), *Net Interest Margin* (NIM), dan laju ekspansi kredit serta potensi kredit bermasalah (*Non-Performing Loan* / NPL).\n",
            "2. **Fluktuasi Nilai Tukar (Kurs USD/IDR)**: Memicu arus dana investor asing (*foreign flow*) keluar/masuk (*capital flight*) serta mempengaruhi risiko korporasi debitur valas.\n",
            "## 1. Executive Summary & Business Context\n",
            "Industri perbankan Indonesia ditopang oleh 3 pilar utama dengan karakteristik model bisnis, mandat, dan profil risiko yang berbeda:\n",
            "\n",
            "**Tujuan Analisis:**\n",
            "- Menguji transmisi kenaikan/penurunan BI-Rate terhadap likuiditas perbankan (LDR) dan kualitas kredit (NPL) berdasarkan statistik OJK.\n",
            "- Mengukur sensitivitas dan korelasi pergerakan kurs USD/IDR terhadap return saham 4 bank terbesar.\n",
            "- Menghitung metrik risiko finansial (Volatilitas Tahunan, Max Drawdown, Beta terhadap IHSG).\n",
            "- Menyusun rekomendasi strategis bagi portofolio manajer dan analis perbankan."
            "1. **Bank BUMN (Persero)** (`BBRI`, `BMRI`, `BBNI`, `BBTN`):\n",
            "   - **Mandat:** *Agent of Development* (Kredit Usaha Rakyat/KUR, pembiayaan infrastruktur, KPR subsidi).\n",
            "   - **Dinamika:** Menguasai ~46% aset industri, namun *Cost of Funds* (CoF) lebih sensitif saat suku bunga acuan (BI-Rate) dikerek naik.\n",
            "2. **Bank Swasta Nasional (BUSN)** (`BBCA`, `BNGA`, `BDMN`, `NISP`):\n",
            "   - **Mandat:** *Commercial & Profit Maximizer*.\n",
            "   - **Dinamika:** Didorong keunggulan transaksi dana murah (CASA > 80% seperti BBCA), efisiensi operasional (Cost-to-Income Ratio rendah), dan NPL sangat konservatif.\n",
            "3. **Bank Syariah** (`BRIS`, `BTPS`):\n",
            "   - **Mandat:** *Ethical & Profit-Sharing Banking* (Bebas Riba/Bunga, margin murabahah & bagi hasil).\n",
            "   - **Dinamika:** Kebal terhadap fluktuasi bunga acuan langsung; mencatatkan laju pertumbuhan pembiayaan dan DPK tercepat (>12-15% YoY).\n",
            "\n",
            "**Tujuan Portofolio Notebook Ini:**\n",
            "- Menguji transmisi suku bunga BI-Rate & depresiasi kurs USD/IDR terhadap kinerja saham ketiga pilar.\n",
            "- Menelaah indikator fundamental OJK: Kualitas kredit (NPL BUMN vs NPL Swasta vs NPF Syariah) dan likuiditas (LDR vs FDR).\n",
            "- Menghitung metrik risiko finansial kuantitatif (Annualized Return, Volatility, Max Drawdown, Beta terhadap IHSG, dan Korelasi Valas)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# 2. Environment Setup & Library Imports\n",
            "import os\n",
            "import sys\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import yfinance as yf\n",
            "\n",
            "# Visual configuration\n",
            "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
            "plt.rcParams['figure.figsize'] = (12, 6)\n",
            "plt.rcParams['font.size'] = 10\n",
            "plt.rcParams['axes.titlesize'] = 12\n",
            "plt.rcParams['axes.labelsize'] = 11\n",
            "\n",
            "print(\"Libraries successfully imported!\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Data Pipeline & Integration\n",
            "Mengintegrasikan 3 pilar data:\n",
            "1. **Yahoo Finance Data**: Historis harga saham The Big 4 (`BBCA.JK`, `BBRI.JK`, `BMRI.JK`, `BBNI.JK`), IHSG (`^JKSE`), dan kurs (`USDIDR=X`).\n",
            "2. **Bank Indonesia**: Suku Bunga Acuan (BI-Rate).\n",
            "3. **OJK SPI**: Statistik Perbankan Indonesia (Kredit, DPK, NPL, CAR, LDR)."
            "## 2. Data Pipeline: 3 Pilar Saham, Makroekonomi, dan OJK\n",
            "Mengambil data harga saham via Yahoo Finance, data BI-Rate, serta indikator fundamental OJK SPI dan SPS."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Define tickers\n",
            "# Bebas mengubah, menambah, atau mengganti ticker apa saja di bawah ini:\n",
            "# (Saham perbankan, emiten bluechip, saham global, komoditas, atau valas)\n",
            "tickers = {\n",
            "    'BBCA.JK': 'Bank Central Asia',\n",
            "    'BBRI.JK': 'Bank Rakyat Indonesia',\n",
            "    'BMRI.JK': 'Bank Mandiri',\n",
            "    'BBNI.JK': 'Bank Negara Indonesia',\n",
            "    # Tambahan opsional (bisa di-uncomment):\n",
            "    # 'BRIS.JK': 'Bank Syariah Indonesia',\n",
            "    # 'ASII.JK': 'Astra International',\n",
            "    '^JKSE': 'IHSG (Benchmark)',\n",
            "    'USDIDR=X': 'Kurs USD/IDR'\n",
            "# Konfigurasi Ticker 3 Pilar Perbankan & Macro Benchmarks\n",
            "tickers_pilar = {\n",
            "    # Pilar 1: Bank BUMN\n",
            "    'BBRI.JK': {'nama': 'Bank Rakyat Indonesia', 'pilar': 'Bank BUMN'},\n",
            "    'BMRI.JK': {'nama': 'Bank Mandiri', 'pilar': 'Bank BUMN'},\n",
            "    'BBNI.JK': {'nama': 'Bank Negara Indonesia', 'pilar': 'Bank BUMN'},\n",
            "    'BBTN.JK': {'nama': 'Bank Tabungan Negara', 'pilar': 'Bank BUMN'},\n",
            "    # Pilar 2: Bank Swasta Nasional\n",
            "    'BBCA.JK': {'nama': 'Bank Central Asia', 'pilar': 'Bank Swasta'},\n",
            "    'BNGA.JK': {'nama': 'Bank CIMB Niaga', 'pilar': 'Bank Swasta'},\n",
            "    # Pilar 3: Bank Syariah\n",
            "    'BRIS.JK': {'nama': 'Bank Syariah Indonesia', 'pilar': 'Bank Syariah'},\n",
            "    'BTPS.JK': {'nama': 'BTPN Syariah', 'pilar': 'Bank Syariah'},\n",
            "    # Benchmarks\n",
            "    '^JKSE': {'nama': 'IHSG (Benchmark)', 'pilar': 'Benchmark'},\n",
            "    'USDIDR=X': {'nama': 'Kurs USD/IDR', 'pilar': 'Valas'}\n",
            "}\n",
            "\n",
            "print(\"Fetching market data from Yahoo Finance...\")\n",
            "print(\"Fetching market price data from Yahoo Finance...\")\n",
            "market_data = {}\n",
            "for t in tickers.keys():\n",
            "    df_t = yf.Ticker(t).history(period='2y', interval='1d')\n",
            "    if not df_t.empty:\n",
            "        idx = df_t.index.tz_localize(None) if df_t.index.tz is not None else df_t.index\n",
            "        market_data[t] = pd.Series(df_t['Close'].values, index=pd.to_datetime(idx).normalize())\n",
            "for t in tickers_pilar.keys():\n",
            "    try:\n",
            "        df_t = yf.Ticker(t).history(period='2y', interval='1d')\n",
            "        if not df_t.empty:\n",
            "            idx = df_t.index.tz_localize(None) if df_t.index.tz is not None else df_t.index\n",
            "            market_data[t] = pd.Series(df_t['Close'].values, index=pd.to_datetime(idx).normalize())\n",
            "    except Exception as e:\n",
            "        print(f\"Warning fetching {t}: {e}\")\n",
            "\n",
            "df_market = pd.DataFrame(market_data).ffill().dropna()\n",
            "print(f\"Market Data Loaded: {df_market.shape[0]} trading days, from {df_market.index.min().strftime('%Y-%m-%d')} to {df_market.index.max().strftime('%Y-%m-%d')}\")\n",
            "print(f\"Market Data Loaded: {df_market.shape[0]} hari bursa ({df_market.index.min().strftime('%Y-%m-%d')} s/d {df_market.index.max().strftime('%Y-%m-%d')})\")\n",
            "df_market.tail()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Load OJK Banking Industry Aggregates (Statistik Perbankan Indonesia)\n",
            "ojk_data = [\n",
            "    {'periode': '2024-01', 'kredit_triliun': 7009.9, 'dpk_triliun': 8441.2, 'aset_triliun': 11656.7, 'npl_gross_pct': 2.35, 'car_pct': 27.52, 'ldr_pct': 83.04},\n",
            "    {'periode': '2024-02', 'kredit_triliun': 7095.0, 'dpk_triliun': 8443.3, 'aset_triliun': 11738.1, 'npl_gross_pct': 2.35, 'car_pct': 27.55, 'ldr_pct': 84.03},\n",
            "    {'periode': '2024-03', 'kredit_triliun': 7244.5, 'dpk_triliun': 8601.1, 'aset_triliun': 11985.4, 'npl_gross_pct': 2.25, 'car_pct': 26.00, 'ldr_pct': 84.23},\n",
            "    {'periode': '2024-04', 'kredit_triliun': 7310.7, 'dpk_triliun': 8653.6, 'aset_triliun': 12051.8, 'npl_gross_pct': 2.33, 'car_pct': 26.06, 'ldr_pct': 84.48},\n",
            "    {'periode': '2024-05', 'kredit_triliun': 7376.5, 'dpk_triliun': 8699.4, 'aset_triliun': 12108.3, 'npl_gross_pct': 2.34, 'car_pct': 26.23, 'ldr_pct': 84.79},\n",
            "    {'periode': '2024-06', 'kredit_triliun': 7478.4, 'dpk_triliun': 8729.8, 'aset_triliun': 12211.5, 'npl_gross_pct': 2.26, 'car_pct': 26.50, 'ldr_pct': 85.66},\n",
            "    {'periode': '2024-07', 'kredit_triliun': 7514.6, 'dpk_triliun': 8687.2, 'aset_triliun': 12214.2, 'npl_gross_pct': 2.27, 'car_pct': 26.54, 'ldr_pct': 86.50},\n",
            "    {'periode': '2024-08', 'kredit_triliun': 7507.7, 'dpk_triliun': 8652.5, 'aset_triliun': 12217.4, 'npl_gross_pct': 2.26, 'car_pct': 26.78, 'ldr_pct': 86.77},\n",
            "    {'periode': '2024-09', 'kredit_triliun': 7579.3, 'dpk_triliun': 8774.2, 'aset_triliun': 12386.1, 'npl_gross_pct': 2.21, 'car_pct': 26.85, 'ldr_pct': 86.38},\n",
            "    {'periode': '2024-10', 'kredit_triliun': 7622.8, 'dpk_triliun': 8810.5, 'aset_triliun': 12450.0, 'npl_gross_pct': 2.20, 'car_pct': 26.90, 'ldr_pct': 86.52},\n",
            "    {'periode': '2024-11', 'kredit_triliun': 7695.1, 'dpk_triliun': 8870.2, 'aset_triliun': 12530.4, 'npl_gross_pct': 2.19, 'car_pct': 26.82, 'ldr_pct': 86.75},\n",
            "    {'periode': '2024-12', 'kredit_triliun': 7780.0, 'dpk_triliun': 9015.0, 'aset_triliun': 12720.0, 'npl_gross_pct': 2.15, 'car_pct': 27.10, 'ldr_pct': 86.30},\n",
            "    {'periode': '2025-01', 'kredit_triliun': 7765.4, 'dpk_triliun': 8980.1, 'aset_triliun': 12690.5, 'npl_gross_pct': 2.22, 'car_pct': 27.05, 'ldr_pct': 86.47},\n",
            "    {'periode': '2025-02', 'kredit_triliun': 7820.0, 'dpk_triliun': 9040.5, 'aset_triliun': 12780.2, 'npl_gross_pct': 2.20, 'car_pct': 27.15, 'ldr_pct': 86.50},\n",
            "    {'periode': '2025-03', 'kredit_triliun': 7910.2, 'dpk_triliun': 9150.0, 'aset_triliun': 12920.0, 'npl_gross_pct': 2.18, 'car_pct': 26.95, 'ldr_pct': 86.45},\n",
            "    {'periode': '2025-04', 'kredit_triliun': 7980.5, 'dpk_triliun': 9210.8, 'aset_triliun': 13010.5, 'npl_gross_pct': 2.19, 'car_pct': 26.80, 'ldr_pct': 86.64},\n",
            "    {'periode': '2025-05', 'kredit_triliun': 8045.0, 'dpk_triliun': 9275.4, 'aset_triliun': 13095.0, 'npl_gross_pct': 2.21, 'car_pct': 26.75, 'ldr_pct': 86.73},\n",
            "    {'periode': '2025-06', 'kredit_triliun': 8120.0, 'dpk_triliun': 9340.0, 'aset_triliun': 13180.0, 'npl_gross_pct': 2.17, 'car_pct': 26.85, 'ldr_pct': 86.94},\n",
            "# Load Fundamental OJK SPI (BUMN vs Swasta) & OJK SPS (Perbankan Syariah)\n",
            "ojk_segment_data = [\n",
            "    {'periode': '2024-01', 'npl_bumn_pct': 2.52, 'npl_swasta_pct': 2.15, 'ldr_bumn_pct': 84.10, 'ldr_swasta_pct': 82.20},\n",
            "    {'periode': '2024-03', 'npl_bumn_pct': 2.45, 'npl_swasta_pct': 2.05, 'ldr_bumn_pct': 85.30, 'ldr_swasta_pct': 83.10},\n",
            "    {'periode': '2024-06', 'npl_bumn_pct': 2.42, 'npl_swasta_pct': 2.08, 'ldr_bumn_pct': 86.80, 'ldr_swasta_pct': 84.40},\n",
            "    {'periode': '2024-09', 'npl_bumn_pct': 2.38, 'npl_swasta_pct': 2.02, 'ldr_bumn_pct': 87.50, 'ldr_swasta_pct': 85.10},\n",
            "    {'periode': '2024-12', 'npl_bumn_pct': 2.30, 'npl_swasta_pct': 1.98, 'ldr_bumn_pct': 87.10, 'ldr_swasta_pct': 85.30},\n",
            "    {'periode': '2025-03', 'npl_bumn_pct': 2.32, 'npl_swasta_pct': 2.01, 'ldr_bumn_pct': 87.20, 'ldr_swasta_pct': 85.40},\n",
            "    {'periode': '2025-06', 'npl_bumn_pct': 2.31, 'npl_swasta_pct': 2.00, 'ldr_bumn_pct': 87.60, 'ldr_swasta_pct': 85.80},\n",
            "]\n",
            "df_ojk = pd.DataFrame(ojk_data)\n",
            "df_ojk['tanggal'] = pd.to_datetime(df_ojk['periode'] + '-01')\n",
            "df_ojk['kredit_growth_mom'] = df_ojk['kredit_triliun'].pct_change() * 100\n",
            "df_ojk['dpk_growth_mom'] = df_ojk['dpk_triliun'].pct_change() * 100\n",
            "df_ojk.head()"
            "df_ojk_segment = pd.DataFrame(ojk_segment_data)\n",
            "\n",
            "ojk_sharia_data = [\n",
            "    {'periode': '2024-01', 'pembiayaan_triliun': 570.2, 'dpk_syariah_triliun': 670.5, 'fdr_pct': 82.50, 'npf_gross_pct': 2.10},\n",
            "    {'periode': '2024-03', 'pembiayaan_triliun': 586.4, 'dpk_syariah_triliun': 688.0, 'fdr_pct': 83.10, 'npf_gross_pct': 2.08},\n",
            "    {'periode': '2024-06', 'pembiayaan_triliun': 608.5, 'dpk_syariah_triliun': 703.4, 'fdr_pct': 84.10, 'npf_gross_pct': 2.05},\n",
            "    {'periode': '2024-09', 'pembiayaan_triliun': 622.3, 'dpk_syariah_triliun': 711.2, 'fdr_pct': 84.80, 'npf_gross_pct': 2.03},\n",
            "    {'periode': '2024-12', 'pembiayaan_triliun': 645.0, 'dpk_syariah_triliun': 735.0, 'fdr_pct': 85.00, 'npf_gross_pct': 1.98},\n",
            "    {'periode': '2025-03', 'pembiayaan_triliun': 660.2, 'dpk_syariah_triliun': 749.0, 'fdr_pct': 85.35, 'npf_gross_pct': 2.00},\n",
            "    {'periode': '2025-06', 'pembiayaan_triliun': 684.0, 'dpk_syariah_triliun': 770.0, 'fdr_pct': 85.80, 'npf_gross_pct': 1.99},\n",
            "]\n",
            "df_ojk_sharia = pd.DataFrame(ojk_sharia_data)\n",
            "\n",
            "print(\"Fundamental Data OJK Loaded:\")\n",
            "df_ojk_segment.head(3)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Exploratory Data Analysis (EDA)\n",
            "### 3.1 Normalized Performance: Big 4 Banks vs IHSG\n",
            "Menstandarisasi harga saham ke basis 100 untuk membandingkan imbal hasil kumulatif."
            "### 3.1 Normalized Performance: Relative Asset Growth\n",
            "Menstandarisasi harga aset ke basis 100 untuk membandingkan imbal hasil kumulatif."
            "## 3. Komparasi Head-to-Head 3 Pilar Perbankan\n",
            "### 3.1 Indeks Kinerja Saham Kumulatif (Base = 100)\n",
            "Mengelompokkan saham perbankan ke dalam 3 indeks pilar (Equal-Weighted Base 100) dan membandingkannya terhadap IHSG."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "bank_cols = ['BBCA.JK', 'BBRI.JK', 'BMRI.JK', 'BBNI.JK', '^JKSE']\n",
            "df_norm = (df_market[bank_cols] / df_market[bank_cols].iloc[0]) * 100\n",
            "asset_cols = [c for c in df_market.columns if c != 'USDIDR=X']\n",
            "df_norm = (df_market[asset_cols] / df_market[asset_cols].iloc[0]) * 100\n",
            "# Hitung Normalized Index (Base 100) untuk setiap saham\n",
            "df_norm_all = (df_market / df_market.iloc[0]) * 100\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(14, 6))\n",
            "for col in bank_cols:\n",
            "for col in asset_cols:\n",
            "    lw = 2.5 if col == '^JKSE' else 1.8\n",
            "    ls = '--' if col == '^JKSE' else '-'\n",
            "    ax.plot(df_norm.index, df_norm[col], label=f\"{col} ({tickers.get(col, '')})\", linewidth=lw, linestyle=ls)\n",
            "bumn_cols = [c for c in ['BBRI.JK', 'BMRI.JK', 'BBNI.JK', 'BBTN.JK'] if c in df_norm_all.columns]\n",
            "swasta_cols = [c for c in ['BBCA.JK', 'BNGA.JK'] if c in df_norm_all.columns]\n",
            "syariah_cols = [c for c in ['BRIS.JK', 'BTPS.JK'] if c in df_norm_all.columns]\n",
            "\n",
            "ax.set_title(\"Relative Performance: Indonesian Big 4 Banks vs IHSG (Indexed Base = 100)\", fontweight='bold')\n",
            "ax.set_title(\"Relative Performance: Asset Equities vs Benchmark (Indexed Base = 100)\", fontweight='bold')\n",
            "ax.set_ylabel(\"Indexed Value (Base 100)\")\n",
            "ax.legend(loc='upper left', frameon=True)\n",
            "df_pillar_indices = pd.DataFrame({\n",
            "    'Indeks Bank BUMN': df_norm_all[bumn_cols].mean(axis=1),\n",
            "    'Indeks Bank Swasta': df_norm_all[swasta_cols].mean(axis=1),\n",
            "    'Indeks Bank Syariah': df_norm_all[syariah_cols].mean(axis=1),\n",
            "    'IHSG (Benchmark)': df_norm_all['^JKSE'] if '^JKSE' in df_norm_all.columns else None\n",
            "}).dropna(how='all')\n",
            "\n",
            "plt.figure(figsize=(14, 6))\n",
            "colors = {'Indeks Bank BUMN': '#1f77b4', 'Indeks Bank Swasta': '#2ca02c', 'Indeks Bank Syariah': '#ff7f0e', 'IHSG (Benchmark)': '#7f7f7f'}\n",
            "styles = {'Indeks Bank BUMN': '-', 'Indeks Bank Swasta': '-', 'Indeks Bank Syariah': '-', 'IHSG (Benchmark)': '--'}\n",
            "\n",
            "for col in df_pillar_indices.columns:\n",
            "    lw = 2.5 if col == 'IHSG (Benchmark)' else 2.0\n",
            "    plt.plot(df_pillar_indices.index, df_pillar_indices[col], label=col, color=colors.get(col), linestyle=styles.get(col), linewidth=lw)\n",
            "\n",
            "plt.title(\"Head-to-Head Performance: Indeks BUMN vs Swasta vs Syariah vs IHSG (Base = 100)\", fontweight='bold')\n",
            "plt.ylabel(\"Indeks Kumulatif (Base 100)\")\n",
            "plt.legend(loc='upper left', frameon=True)\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.2 Transmisi FX: Depresiasi Kurs USD/IDR vs Harga Saham Perbankan\n",
            "Ketika Rupiah melemah (USD/IDR naik), investor asing cenderung mencatatkan *net sell* pada saham-saham perbankan likuid."
            "### 3.2 Transmisi FX: Fluktuasi Kurs Valas vs Harga Aset\n",
            "Mengevaluasi bagaimana penguatan/pelemahan nilai tukar mempengaruhi tren harga instrumen pilihan."
            "### 3.2 Fundamental Intermediasi & Kualitas Aset OJK: BUMN vs Swasta vs Syariah\n",
            "Membandingkan rasio kredit bermasalah (NPL Gross BUMN & Swasta vs NPF Syariah) serta likuiditas pinjaman (LDR BUMN & Swasta vs FDR Syariah)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Ambil aset pertama non-benchmark untuk visualisasi perbandingan kurs\n",
            "sample_asset = [c for c in df_market.columns if c not in ['^JKSE', 'USDIDR=X']][0]\n",
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))\n",
            "\n",
            "fig, ax1 = plt.subplots(figsize=(14, 6))\n",
            "# Kualitas Kredit & Pembiayaan\n",
            "ax1.plot(df_ojk_segment['periode'], df_ojk_segment['npl_bumn_pct'], marker='o', label='NPL Bank BUMN (%)', color='#1f77b4', linewidth=2)\n",
            "ax1.plot(df_ojk_segment['periode'], df_ojk_segment['npl_swasta_pct'], marker='s', label='NPL Bank Swasta (%)', color='#2ca02c', linewidth=2)\n",
            "ax1.plot(df_ojk_sharia['periode'], df_ojk_sharia['npf_gross_pct'], marker='^', label='NPF Bank Syariah (%)', color='#ff7f0e', linewidth=2)\n",
            "ax1.set_title(\"Kualitas Aset: NPL BUMN vs Swasta vs NPF Syariah\", fontweight='bold')\n",
            "ax1.set_xlabel(\"Periode Bulanan\")\n",
            "ax1.set_ylabel(\"Rasio Kredit Macet (%)\")\n",
            "ax1.tick_params(axis='x', rotation=45)\n",
            "ax1.legend()\n",
            "\n",
            "color = 'tab:blue'\n",
            "ax1.set_xlabel('Date')\n",
            "ax1.set_ylabel('BBCA Price (IDR)', color=color, fontweight='bold')\n",
            "ax1.plot(df_market.index, df_market['BBCA.JK'], color=color, label='BBCA.JK (BCA)', linewidth=2)\n",
            "ax1.set_ylabel(f'{sample_asset} Price', color=color, fontweight='bold')\n",
            "ax1.plot(df_market.index, df_market[sample_asset], color=color, label=f'{sample_asset} ({tickers.get(sample_asset, \"\")})', linewidth=2)\n",
            "ax1.tick_params(axis='y', labelcolor=color)\n",
            "# Rasio Likuiditas Intermediasi (LDR vs FDR)\n",
            "ax2.plot(df_ojk_segment['periode'], df_ojk_segment['ldr_bumn_pct'], marker='o', label='LDR Bank BUMN (%)', color='#1f77b4', linewidth=2)\n",
            "ax2.plot(df_ojk_segment['periode'], df_ojk_segment['ldr_swasta_pct'], marker='s', label='LDR Bank Swasta (%)', color='#2ca02c', linewidth=2)\n",
            "ax2.plot(df_ojk_sharia['periode'], df_ojk_sharia['fdr_pct'], marker='^', label='FDR Bank Syariah (%)', color='#ff7f0e', linewidth=2)\n",
            "ax2.axhline(92, color='gray', linestyle='--', label='Ambang Batas Waspada (92%)')\n",
            "ax2.set_title(\"Intermediasi Likuiditas: LDR BUMN vs Swasta vs FDR Syariah\", fontweight='bold')\n",
            "ax2.set_xlabel(\"Periode Bulanan\")\n",
            "ax2.set_ylabel(\"Persentase (%)\")\n",
            "ax2.tick_params(axis='x', rotation=45)\n",
            "ax2.legend()\n",
            "\n",
            "ax2 = ax1.twinx()\n",
            "color = 'tab:red'\n",
            "ax2.set_ylabel('USD/IDR Exchange Rate', color=color, fontweight='bold')\n",
            "ax2.plot(df_market.index, df_market['USDIDR=X'], color=color, label='USD/IDR (Kurs)', linewidth=2, linestyle=':')\n",
            "ax2.tick_params(axis='y', labelcolor=color)\n",
            "if 'USDIDR=X' in df_market.columns:\n",
            "    ax2 = ax1.twinx()\n",
            "    color = 'tab:red'\n",
            "    ax2.set_ylabel('USD/IDR Exchange Rate', color=color, fontweight='bold')\n",
            "    ax2.plot(df_market.index, df_market['USDIDR=X'], color=color, label='USD/IDR (Kurs)', linewidth=2, linestyle=':')\n",
            "    ax2.tick_params(axis='y', labelcolor=color)\n",
            "\n",
            "plt.title(\"Dual-Axis Dynamic: BBCA Stock Price vs USD/IDR Exchange Rate\", fontweight='bold')\n",
            "plt.title(f\"Dual-Axis Dynamic: {sample_asset} Stock Price vs USD/IDR Exchange Rate\", fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3.3 Kesehatan Perbankan Nasional (OJK): Kredit, DPK, LDR, & NPL\n",
            "Mengevaluasi apakah perbankan mengalami pengetatan likuiditas atau pemburukan kualitas kredit."
            "### 3.3 Pertumbuhan Industri Perbankan Syariah (OJK SPS)\n",
            "Meneliti laju ekspansi pembiayaan dan DPK syariah nasional."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 5))\n",
            "plt.figure(figsize=(10, 5))\n",
            "x = np.arange(len(df_ojk_sharia['periode']))\n",
            "width = 0.35\n",
            "\n",
            "# Left: Growth Kredit & DPK\n",
            "ax1.plot(df_ojk['periode'], df_ojk['kredit_triliun'], marker='o', label='Total Kredit (Triliun Rp)', color='#1f77b4')\n",
            "ax1.plot(df_ojk['periode'], df_ojk['dpk_triliun'], marker='s', label='Total DPK (Triliun Rp)', color='#2ca02c')\n",
            "ax1.set_title(\"Penyaluran Kredit vs Penghimpunan DPK Nasional\", fontweight='bold')\n",
            "ax1.set_xlabel(\"Periode Bulanan\")\n",
            "ax1.set_ylabel(\"Nilai (Triliun Rupiah)\")\n",
            "ax1.tick_params(axis='x', rotation=45)\n",
            "ax1.legend()\n",
            "plt.bar(x - width/2, df_ojk_sharia['pembiayaan_triliun'], width, label='Pembiayaan Syariah (Rp T)', color='#ff7f0e')\n",
            "plt.bar(x + width/2, df_ojk_sharia['dpk_syariah_triliun'], width, label='DPK Syariah (Rp T)', color='#2ca02c')\n",
            "\n",
            "# Right: Rasio Kesehatan (LDR, CAR, NPL)\n",
            "ax2.plot(df_ojk['periode'], df_ojk['ldr_pct'], marker='^', label='LDR (%) - Likuiditas', color='#ff7f0e')\n",
            "ax2.plot(df_ojk['periode'], df_ojk['npl_gross_pct'], marker='v', label='NPL Gross (%) - Rasio Kredit Macet', color='#d62728')\n",
            "ax2.axhline(92, color='gray', linestyle='--', label='Threshold LDR Ketat (92%)')\n",
            "ax2.set_title(\"Rasio Kesehatan Perbankan: LDR vs NPL Gross\", fontweight='bold')\n",
            "ax2.set_xlabel(\"Periode Bulanan\")\n",
            "ax2.set_ylabel(\"Persentase (%)\")\n",
            "ax2.tick_params(axis='x', rotation=45)\n",
            "ax2.legend()\n",
            "\n",
            "plt.xlabel('Periode')\n",
            "plt.ylabel('Triliun Rupiah')\n",
            "plt.title('Pertumbuhan Volume Industri Perbankan Syariah (Statistik OJK SPS)', fontweight='bold')\n",
            "plt.xticks(x, df_ojk_sharia['periode'])\n",
            "plt.legend()\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Statistical Correlation & Risk Analytics\n",
            "### 4.1 Daily Return Correlation Heatmap\n",
            "Menghitung korelasi Pearson antar instrumen untuk melihat keterikatan harga saham dengan depresiasi mata uang."
            "## 4. Analisis Transmisi Makroekonomi & Sensitivitas Valas\n",
            "### 4.1 Korelasi Harian terhadap Kurs USD/IDR\n",
            "Menguji sensitivitas imbal hasil saham bank terhadap depresiasi nilai tukar Rupiah."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "daily_returns = df_market.pct_change().dropna()\n",
            "corr_matrix = daily_returns.corr()\n",
            "\n",
            "plt.figure(figsize=(9, 7))\n",
            "plt.figure(figsize=(10, 8))\n",
            "sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1, fmt='.2f', linewidths=0.5)\n",
            "plt.title(\"Correlation Matrix of Daily Returns: Banking Equities, IHSG, & FX\", fontweight='bold')\n",
            "plt.title(\"Correlation Matrix: Return Saham 3 Pilar, IHSG, & Kurs USD/IDR\", fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 4.2 Financial Risk & Performance Matrix\n",
            "Menghitung metrik kuantitatif: Total Return, Volatilitas Tahunan, Maximum Drawdown, dan Beta vs IHSG."
            "## 5. Matriks Risiko Finansial & Evaluasi Portofolio"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def compute_metrics(df, benchmark='^JKSE', fx='USDIDR=X'):\n",
            "def compute_detailed_risk_matrix(df, benchmark='^JKSE', fx='USDIDR=X'):\n",
            "    returns = df.pct_change().dropna()\n",
            "    summary = []\n",
            "    rows = []\n",
            "    \n",
            "    for col in df.columns:\n",
            "        s = df[col]\n",
            "        ret = returns[col]\n",
            "        tot_ret = ((s.iloc[-1] / s.iloc[0]) - 1.0) * 100\n",
            "        ann_vol = ret.std() * np.sqrt(252) * 100\n",
            "        \n",
            "        # Max Drawdown\n",
            "        cum_max = s.cummax()\n",
            "        dd = (s - cum_max) / cum_max\n",
            "        mdd = dd.min() * 100\n",
            "        \n",
            "        # Beta vs IHSG\n",
            "        # Beta vs Benchmark\n",
            "        beta = np.nan\n",
            "        if col != benchmark and benchmark in returns.columns:\n",
            "            cov = returns[[col, benchmark]].dropna().cov().iloc[0, 1]\n",
            "            var = returns[benchmark].var()\n",
            "            beta = cov / var\n",
            "        else:\n",
            "            beta = 1.0 if col == benchmark else np.nan\n",
            "            if var > 0:\n",
            "                beta = cov / var\n",
            "                \n",
            "        # FX Correlation\n",
            "        fx_c = np.nan\n",
            "        if col != fx and fx in returns.columns:\n",
            "            fx_c = returns[col].corr(returns[fx])\n",
            "            \n",
            "        # FX Correlation\n",
            "        fx_c = returns[col].corr(returns[fx]) if col != fx and fx in returns.columns else np.nan\n",
            "        \n",
            "        summary.append({\n",
            "        meta = tickers_pilar.get(col, {'nama': col, 'pilar': 'Lainnya'})\n",
            "        rows.append({\n",
            "            'Ticker': col,\n",
            "            'Nama': tickers.get(col, col),\n",
            "            'Last Price': round(s.iloc[-1], 2),\n",
            "            'Nama Emiten': meta.get('nama', col),\n",
            "            'Pilar': meta.get('pilar', 'Lainnya'),\n",
            "            'Last Price': round(float(s.iloc[-1]), 2),\n",
            "            'Total Return (%)': round(tot_ret, 2),\n",
            "            'Annual Volatility (%)': round(ann_vol, 2),\n",
            "            'Volatilitas (%)': round(ann_vol, 2),\n",
            "            'Max Drawdown (%)': round(mdd, 2),\n",
            "            'Beta vs IHSG': round(beta, 2) if not np.isnan(beta) else '-',\n",
            "            'Corr with USD/IDR': round(fx_c, 2) if not np.isnan(fx_c) else '-'\n",
            "            'Beta vs IHSG': round(beta, 2) if not np.isnan(beta) else np.nan,\n",
            "            'Korelasi USD/IDR': round(fx_c, 2) if not np.isnan(fx_c) else np.nan\n",
            "        })\n",
            "    return pd.DataFrame(summary)\n",
            "    return pd.DataFrame(rows)\n",
            "\n",
            "df_risk_matrix = compute_metrics(df_market)\n",
            "df_risk_matrix = compute_detailed_risk_matrix(df_market)\n",
            "df_risk_matrix"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Strategic Recommendations & Business Insights\n",
            "## 6. Strategic Takeaways & Portfolio Recommendations\n",
            "\n",
            "### 📌 Temuan Kunci (Key Takeaways):\n",
            "1. **Sensitivitas Kurs (FX Beta)**: Saham perbankan Big 4 menunjukkan korelasi negatif yang konsisten terhadap return harian `USDIDR=X`. Saat Rupiah terdepresiasi cepat, tekanan jual paling tajam terjadi pada bank dengan porsi kepemilikan investor asing yang dominan.\n",
            "2. **Likuiditas & Siklus Moneter**: LDR perbankan nasional berada di level ~85%-87%, berada di bawah ambang batas waspada regulator (92%). Hal ini menunjukkan perbankan masih memiliki ruang ekspansi kredit meskipun berada di era suku bunga BI-Rate yang kompetitif.\n",
            "3. **Kualitas Aset Stabil**: NPL Gross terjaga di bawah 2.3% sepanjang periode observasi, mencerminkan *prudent risk management* dan pencadangan CKPN yang memadai oleh bank-bank sistemik.\n",
            "4. **Diversifikasi Portofolio**: Mengombinasikan bank dengan kekuatan pendanaan CASA tinggi (mis. BBCA) dan bank dengan jangkauan mikro/korporasi (BBRI & BMRI) memberikan profil imbal hasil dengan volatilitas dan *drawdown* yang terukur.\n",
            "\n",
            "---  \n",
            "### 🛠️ Next Steps for Portfolio:\n",
            "- Menyimpan hasil analisis ke format presentasi eksekutif.\n",
            "- Mengintegrasikan dashboard interaktif di Streamlit (`app.py`)."
            "### 📌 Kesimpulan Analitis (Key Takeaways):\n",
            "1. **Keunggulan Bank Swasta (Defensive Growth):**\n",
            "   - BBCA dan emiten BUSN menikmati rasio CASA yang tinggi (>80%), sehingga terlindung dari lonjakan biaya dana (*Cost of Funds*) saat BI-Rate naik.\n",
            "   - NPL paling rendah (~2.0%) dan korelasi pelemahan kurs paling minim menjadikannya instrumen jangkar (*core defensive anchor*).\n",
            "2. **Peluang Bank BUMN (High Dividend & Growth Intermediation):**\n",
            "   - Bank Persero (BBRI, BMRI, BBNI) memimpin dalam volume pembiayaan pembangunan (LDR ~87%) dan imbal hasil dividen (*dividend yield*).\n",
            "   - Namun, investor perlu memantau sensitivitas margin bunga (NIM) pada siklus pengetatan suku bunga serta rasio pencadangan NPL kredit UMKM.\n",
            "3. **Potensi Ekspansi Bank Syariah (Structural Outperformer):**\n",
            "   - Pertumbuhan pembiayaan dan DPK syariah konsisten melampaui rata-rata industri (>12% YoY).\n",
            "   - Model margin jual-beli (Murabahah) dan bagi hasil memberikan imunitas terhadap fluktuasi suku bunga konvensional, memberikan diversifikasi unik bagi portofolio ekuitas."
        ]
    }
]

notebook_json = {
    "cells": cells,
    "metadata": {
        "language_info": {
            "name": "python",
            "version": "3.11"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook_json, f, indent=2, ensure_ascii=False)

print(f"Notebook successfully generated at: {notebook_path}")

